# openshift/ocp-bc.yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: demo-app
  namespace: demo-cicd
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-app
  namespace: demo-cicd
spec:
  source:
    type: Binary             # <— Jenkins enviará el contexto
  strategy:
    type: Docker             # <— usa tu Dockerfile
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: demo-app:latest  # <— destino en el registry interno
